from decimal import Decimal
from enum import Enum
from typing import Mapping, Protocol, Self

type BuiltFeatures = Mapping[Enum, int | Decimal | float]


class NormalTransactionsFeatureBuilder(Protocol):
    def total_ether_send(self) -> Self: ...

    def min_value_send(self) -> Self: ...

    def max_value_send(self) -> Self: ...

    def total_ether_recv(self) -> Self: ...

    def min_value_recv(self) -> Self: ...

    def max_value_recv(self) -> Self: ...

    def avg_sent(self) -> Self: ...

    def avg_recv(self) -> Self: ...

    def unique_sent(self) -> Self: ...

    def unique_recv(self) -> Self: ...

    def time_diff(self) -> Self: ...

    def avg_min_between_sent_tnx(self) -> Self: ...

    def sent_tnx(self) -> Self: ...

    def received_tnx(self) -> Self: ...

    def unique_sent_to_addresses(self) -> Self: ...

    def unique_received_from_addresses(self) -> Self: ...

    def avg_min_between_received_tnx(self) -> Self: ...

    def build(self) -> BuiltFeatures: ...


class InternalTransactionsFeatureBuilder(Protocol):
    def number_of_created_contracts(self) -> Self: ...

    def total_ether_sent_contracts(self) -> Self: ...

    def build(self) -> BuiltFeatures: ...


class TokenTransfersFeatureBuilder(Protocol):
    def total_erc20_tnx(self) -> Self: ...

    def erc20_total_ether_sent(self) -> Self: ...

    def erc20_total_ether_received(self) -> Self: ...

    def erc20_uniq_sent_addr(self) -> Self: ...

    def erc20_uniq_rec_addr(self) -> Self: ...

    def erc20_uniq_rec_contract_addr(self) -> Self: ...

    def erc20_min_val_sent(self) -> Self: ...

    def erc20_max_val_sent(self) -> Self: ...

    def erc20_avg_val_sent(self) -> Self: ...

    def erc20_min_val_rec(self) -> Self: ...

    def erc20_max_val_rec(self) -> Self: ...

    def erc20_avg_val_rec(self) -> Self: ...

    def erc20_uniq_sent_token_name(self) -> Self: ...

    def erc20_uniq_rec_token_name(self) -> Self: ...

    def build(self) -> BuiltFeatures: ...


class FeatureExtractionDirector(Protocol):
    def __call__(self) -> BuiltFeatures: ...
