from enum import Enum


class FeaturesEnum(Enum):
    TOTAL_ETHEREUM_SENT = "TOTAL_ETHEREUM_SEND"
    MIN_VALUE_SENT = "MIN_VALUE_SEND"
    MAX_VALUE_SENT = "MAX_VALUE_SEND"
    TOTAL_ETHEREUM_REC = "TOTAL_ETHEREUM_REC"
    MIN_VALUE_REC = "MIN_VALUE_REC"
    MAX_VALUE_REC = "MAX_VALUE_REC"
    AVG_SENT = "AVG_SENT"
    AVG_REC = "AVG_REC"
    UNIQUE_SENT = "UNIQUE_SENT"
    UNIQUE_RECV = "UNIQUE_RECV"
    TIME_DIFF_FIRST_LAST = "TIME_DIFF_FIRST_LAST"
    AVG_TIME_BETWEEN_SENT = "AVG_TIME_BETWEEN_SENT"
    SENT_TNX = "SENT_TNX"
    RECEIVED_TNX = "RECEIVED_TNX"
    UNIQUE_SENT_TO_ADDRESSES = "UNIQUE_SENT_TO_ADDRESSES"
    UNIQUE_RECEIVED_FROM_ADDRESSES = "UNIQUE_RECEIVED_FROM_ADDRESSES"
    AVG_TIME_BETWEEN_RECEIVED = "AVG_TIME_BETWEEN_RECEIVED"
