from enum import Enum


class FeaturesEnum(Enum):
    TOTAL_ETHEREUM_SENT = "TOTAL_ETHEREUM_SEND"
    MIN_VALUE_SENT = "MIN_VALUE_SEND"
    MAX_VALUE_SENT = "MAX_VALUE_SEND"
    TOTAL_ETHEREUM_REC = "TOTAL_ETHEREUM_REC"
    MIN_VALUE_REC = "MIN_VALUE_REC"
    MAX_VALUE_REC = "MAX_VALUE_REC"
    AVG_SENT = "AVG_SENT"
    AVG_REC = "AVG_REC"
    UNIQUE_SENT = "UNIQUE_SENT"
    UNIQUE_RECV = "UNIQUE_RECV"
    TIME_DIFF_FIRST_LAST = "TIME_DIFF_FIRST_LAST"
    AVG_TIME_BETWEEN_SENT = "AVG_TIME_BETWEEN_SENT"
    SENT_TNX = "SENT_TNX"
    RECEIVED_TNX = "RECEIVED_TNX"
    UNIQUE_SENT_TO_ADDRESSES = "UNIQUE_SENT_TO_ADDRESSES"
    UNIQUE_RECEIVED_FROM_ADDRESSES = "UNIQUE_RECEIVED_FROM_ADDRESSES"
    AVG_TIME_BETWEEN_RECEIVED = "AVG_TIME_BETWEEN_RECEIVED"
    NUMBER_OF_CREATED_CONTRACTS = "number_of_created_contracts"
    TOTAL_ETHER_SENT_CONTRACTS = "total_ether_sent_contracts"
    TOTAL_ERC20_TNX = "total_erc20_tnx"
    ERC20_TOTAL_ETHER_SENT = "erc20_total_ether_sent"
    ERC20_TOTAL_ETHER_RECEIVED = "erc20_total_ether_received"
    ERC20_UNIQ_SENT_ADDR = "erc20_uniq_sent_addr"
    ERC20_UNIQ_REC_ADDR = "erc20_uniq_rec_addr"
    ERC20_UNIQ_REC_CONTRACT_ADDR = "erc20_uniq_rec_contract_addr"
    ERC20_MIN_VAL_SENT = "erc20_min_val_sent"
    ERC20_MAX_VAL_SENT = "erc20_max_val_sent"
    ERC20_AVG_VAL_SENT = "erc20_avg_val_sent"
    ERC20_MIN_VAL_REC = "erc20_min_val_rec"
    ERC20_MAX_VAL_REC = "erc20_max_val_rec"
    ERC20_AVG_VAL_REC = "erc20_avg_val_rec"
    ERC20_UNIQ_SENT_TOKEN_NAME = "erc20_uniq_sent_token_name"
    ERC20_UNIQ_REC_TOKEN_NAME = "erc20_uniq_rec_token_name"
