from typing import Protocol


class MetricsClient(Protocol):
    def set_inference_latency(self, amount: float | int) -> None: ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc_val, exc_tb): ...

    def timer(self): ...
